---
- name: Install System packages
  apt: pkg={{ item }} state=present
  with_items: "{{ fradee_packages }}"

- name: Configure timezone
  template: src=timezone.j2 dest=/etc/timezone

- name: Configure localtime
  file: src=/usr/share/zoneinfo/{{ fradee_timezone }} dest=/etc/localtime state=link force=yes backup=yes

- name: Installs the specific repos
  apt_repository: repo={{ item }} update_cache=yes state=present
  with_items: "{{ fradee_repos }}"